#ifndef ASSETS_H
#define ASSETS_H

#if defined(BUILD_DEBUG)
#define ASSET_TRACK0   "../../dat/track0.ogg"
#define ASSET_TRACK1   "../../dat/track1.ogg"
#define ASSET_TRACK2   "../../dat/track2.ogg"
#define ASSET_IMGBIT   "../../dat/imgbit.bmp"
#define ASSET_IMGPAL   "../../dat/imgpal.bmp"
#define ASSET_BOOM     "../../dat/boom.wav"
#define ASSET_BREAK    "../../dat/break.wav"
#define ASSET_CODE     "../../dat/code.wav"
#define ASSET_ITEM     "../../dat/item.wav"
#define ASSET_NSHOT0   "../../dat/nshot0.wav"
#define ASSET_NSHOT1   "../../dat/nshot1.wav"
#define ASSET_NSHOT2   "../../dat/nshot2.wav"
#define ASSET_RSHOT0   "../../dat/rshot0.wav"
#define ASSET_RSHOT1   "../../dat/rshot1.wav"
#define ASSET_RSHOT2   "../../dat/rshot2.wav"
#define ASSET_SMACK    "../../dat/smack.wav"
#define ASSET_SQUEAK0  "../../dat/squeak0.wav"
#define ASSET_SQUEAK1  "../../dat/squeak1.wav"
#define ASSET_SQUEAK2  "../../dat/squeak2.wav"
#define ASSET_SSHOT0   "../../dat/sshot0.wav"
#define ASSET_SSHOT1   "../../dat/sshot1.wav"
#define ASSET_SSHOT2   "../../dat/sshot2.wav"
#define ASSET_SWISH    "../../dat/swish.wav"
#define ASSET_TING0    "../../dat/ting0.wav"
#define ASSET_TING1    "../../dat/ting1.wav"
#define ASSET_TING2    "../../dat/ting2.wav"
#define ASSET_ZAP      "../../dat/zap.wav"
#else
#define ASSET_TRACK0   "dat/track0.ogg"
#define ASSET_TRACK1   "dat/track1.ogg"
#define ASSET_TRACK2   "dat/track2.ogg"
#define ASSET_IMGBIT   "dat/imgbit.bmp"
#define ASSET_IMGPAL   "dat/imgpal.bmp"
#define ASSET_BOOM     "dat/boom.wav"
#define ASSET_BREAK    "dat/break.wav"
#define ASSET_CODE     "dat/code.wav"
#define ASSET_ITEM     "dat/item.wav"
#define ASSET_NSHOT0   "dat/nshot0.wav"
#define ASSET_NSHOT1   "dat/nshot1.wav"
#define ASSET_NSHOT2   "dat/nshot2.wav"
#define ASSET_RSHOT0   "dat/rshot0.wav"
#define ASSET_RSHOT1   "dat/rshot1.wav"
#define ASSET_RSHOT2   "dat/rshot2.wav"
#define ASSET_SMACK    "dat/smack.wav"
#define ASSET_SQUEAK0  "dat/squeak0.wav"
#define ASSET_SQUEAK1  "dat/squeak1.wav"
#define ASSET_SQUEAK2  "dat/squeak2.wav"
#define ASSET_SSHOT0   "dat/sshot0.wav"
#define ASSET_SSHOT1   "dat/sshot1.wav"
#define ASSET_SSHOT2   "dat/sshot2.wav"
#define ASSET_SWISH    "dat/swish.wav"
#define ASSET_TING0    "dat/ting0.wav"
#define ASSET_TING1    "dat/ting1.wav"
#define ASSET_TING2    "dat/ting2.wav"
#define ASSET_ZAP      "dat/zap.wav"
#endif

#endif /* ASSETS_H */
